### ISSUE TITLE
How files should be saved in our .env.yml or .env.py

### ISSUE THREAD

**Issue by ladeoshodi** [andela-osule/django-envie#1]
I noticed that .env.yml file configuration should be stored as DB_NAME: "sector_seven" and not DB_NAME = "sector_seven". Is this the same for .env.py??

**Comment by osule** [comment]
Hi, Lade.

I am just seeing this so I'm sorry if this is a late reply.

The  .env.yml format is very different from .env.py.

.env.py uses\* KEY=VALUE\* while the.env.yml uses\* KEY:VALUE*

Regards,

Oluwafemi Sule

**Comment by ladeoshodi** [comment]
Cool, I think it should reflect in your README. 

Also I had a problem using django-envie with Travis even though I had set the same environment i have locally on travis. 

Maybe it's with my configuration. 

You could also reflect using django-envie with TravisCI and CircleCI in your README.

Till Monday.

Cheers.
